cloud_rx/AslPrescriptionApi/Controllers/Calendar/PromotionalCalendarUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AslPrescriptionApi.Models;
using AslPrescriptionApi.Models.ASL;

namespace AslPrescriptionApi.Controllers.Calendar
{
    public class PromotionalCalendarUploadController : AppController
    {
        //Datetime formet
        IFormatProvider dateformat = new System.Globalization.CultureInfo("fr-FR", true);
        TimeZoneInfo timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
        public DateTime td;

        AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();
        //Get Ip ADDRESS,Time & user PC Name
        public string strHostName;
        public IPHostEntry ipHostInfo;
        public IPAddress ipAddress;

        public PromotionalCalendarUploadController()
        {
            strHostName = System.Net.Dns.GetHostName();
            ipHostInfo = Dns.Resolve(Dns.GetHostName());
            ipAddress = ipHostInfo.AddressList[0];
            //td = DateTime.Now;
            td = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
        }


        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file, ASL_PCalendarImage model)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/P_Calendar_images/"), model.Year + model.Month + "_" + fileName);

                    model.FilePath = "/P_Calendar_images/" + model.Year + model.Month + "_" + fileName;
                    var findPreviousImages =
                        (from m in db.CalendarImageDbSet where m.Year == model.Year && m.Month == model.Month select m)
                            .ToList();
                    if (findPreviousImages.Count != 0)
                    {
                        String oldPath = "";
                        foreach (var getPath in findPreviousImages)
                        {
                            oldPath = getPath.FilePath;
                            getPath.FilePath = model.FilePath;
                        }
                        db.SaveChanges();

                        String oldFullPath = Request.MapPath("~" + oldPath);
                        if (System.IO.File.Exists(oldFullPath))
                        {
                            System.IO.File.Delete(oldFullPath);
                        }
                    }
                    else
                    {
                        db.CalendarImageDbSet.Add(model);
                        db.SaveChanges();
                    }

                    file.SaveAs(path);
                    ViewBag.UploadMessage = "Upload successfully done! ";
                }
            }
            catch
            {
                ViewBag.UploadMessage = "Image file is not in correct Format.";
            }


            return View();
        }



        //Get Data From ASL_PCalendarImage Table
        public PartialViewResult CalendarInfo(Int64 year)
        {
            List<ASL_PCalendarImage> calendarImages = new List<ASL_PCalendarImage>();

            calendarImages = db.CalendarImageDbSet.Where(e => e.Year == year).OrderBy(e=>e.Month).ToList();
            return PartialView("~/Views/PromotionalCalendarUpload/_CalendarImageInfo.cshtml", calendarImages);
        }




        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

    }
}

cloud_rx/AslPrescriptionApi/Views/PromotionalCalendarUpload/Index.cshtml
@using AslPrescriptionApi.Models
@using AslPrescriptionApi.Models.DTO
@model AslPrescriptionApi.Models.ASL.ASL_PCalendarImage

@{
    ViewBag.Title = "Index";


    if (HttpContext.Current.Session["LoggedUserType"] == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

    var LoggedUserTp = HttpContext.Current.Session["LoggedUserType"].ToString();
    var LoggedUserStatus = HttpContext.Current.Session["LoggedUserStatus"].ToString();

    if (LoggedUserTp == "AslSuperadmin" && LoggedUserStatus == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }



    List<SelectListItem> listOfYear = new List<SelectListItem>();
    listOfYear.Add(new SelectListItem { Text = "2017", Value = "2017" });
    listOfYear.Add(new SelectListItem { Text = "2018", Value = "2018" });
    listOfYear.Add(new SelectListItem { Text = "2019", Value = "2019" });
    listOfYear.Add(new SelectListItem { Text = "2020", Value = "2020" });
    listOfYear.Add(new SelectListItem { Text = "2021", Value = "2021" });
    listOfYear.Add(new SelectListItem { Text = "2022", Value = "2022" });
    listOfYear.Add(new SelectListItem { Text = "2023", Value = "2023" });
    listOfYear.Add(new SelectListItem { Text = "2024", Value = "2024" });


    List<SelectListItem> listOfMonth = new List<SelectListItem>();
    listOfMonth.Add(new SelectListItem { Text = "January", Value = "01" });
    listOfMonth.Add(new SelectListItem { Text = "February", Value = "02" });
    listOfMonth.Add(new SelectListItem { Text = "March", Value = "03" });
    listOfMonth.Add(new SelectListItem { Text = "April", Value = "04" });
    listOfMonth.Add(new SelectListItem { Text = "May", Value = "05" });
    listOfMonth.Add(new SelectListItem { Text = "June", Value = "06" });
    listOfMonth.Add(new SelectListItem { Text = "July", Value = "07" });
    listOfMonth.Add(new SelectListItem { Text = "August", Value = "08" });
    listOfMonth.Add(new SelectListItem { Text = "September", Value = "09" });
    listOfMonth.Add(new SelectListItem { Text = "October", Value = "10" });
    listOfMonth.Add(new SelectListItem { Text = "November", Value = "11" });
    listOfMonth.Add(new SelectListItem { Text = "December", Value = "12" });

}


@using (Html.BeginForm("Index", "PromotionalCalendarUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


    <div id="contentHeaderBox">
        <h1>Promotional Calendar Upload</h1>
        @*<div class="btn-group pull-right" id="editOption">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-expanded="false">
                    <i class="fa fa-cog"></i>
                </button>
                <ul class="dropdown-menu pull-right" style="" role="menu">
                    <li>
                        <a href="@Url.Action("GroupView", "UploadGroup")"><i class="fa fa-file-text"></i> Contact Group</a>
                        <a href="@Url.Action("EditContact", "UploadEdit")"><i class="fa fa-file-text"></i> Edit Contact</a>
                    </li>
                </ul>
            </div>*@
    </div>
    <br />

    <div class="col-md-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-12">
                    <p>Please upload image file with specific format <strong>(NB: .jpg, .png)</strong></p>
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("name", "Year: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.Year, listOfYear, new { @class = "form-control", id = "txtYear", autofocus = true })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("name", "Month: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.Month, listOfMonth, new { @class = "form-control", id = "txtMonth", autofocus = true })
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("name", "Browse Image: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    <input type="file" id="image1" name="file" accept="image/*" @*accept="image/gif, image/jpeg, image/png"*@ />

                </div>
                <div class="col-md-2">
                    <input type="submit" class="btn btn-primary" value="Process" style="float: right;" id="load" data-loading-text="Uploading...." />
                </div>
                @if (ViewBag.UploadMessage != null)
                {
                    <div class="col-md-4">
                        <h4 style="color: #226699">@ViewBag.UploadMessage</h4>
                    </div>

                }
            </div>

            <br />
            <div id="getCalendarInfo">
                @Html.Partial("~/Views/PromotionalCalendarUpload/_CalendarImageInfo.cshtml")
            </div>

        </div>
    </div>



    <script type="text/javascript">

        $(document).ready(function () {
            var f1 = document.getElementById('image1');

            f1.onchange = function (e) {
                var ext = this.value.match(/\.(.+)$/)[1];
                switch (ext) {
                    case 'jpg':
                    //case 'bmp':
                    case 'png':
                    //case 'tif':
                        alert('allowed');
                        break;
                    default:
                        alert('not allowed');
                        this.value = '';
                }
            };


            var txtyear = $('#txtYear').val();
            $('#getCalendarInfo').load('@Url.Action("CalendarInfo")', { year: txtyear });

            $('#txtYear').change(function () {
                var txtyear = $('#txtYear').val();
                $('#getCalendarInfo').load('@Url.Action("CalendarInfo")', { year: txtyear });
            });

            $('.btn').on('click', function () {
                var $this = $(this);
                $this.button('loading');
                setTimeout(function () {
                    $this.button('reset');
                }, 8000);
            });
        });
    </script>

}

<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.9.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>

cloud_rx/AslPrescriptionApi/Views/PromotionalCalendarUpload/_CalendarImageInfo.cshtml
@using AslPrescriptionApi.Models
@using AslPrescriptionApi.Models.ASL
@model IEnumerable<AslPrescriptionApi.Models.ASL.ASL_PCalendarImage>

@{
    ViewBag.Title = "Index";

    if (HttpContext.Current.Session["LoggedUserType"] == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

    var LoggedUserTp = HttpContext.Current.Session["LoggedUserType"].ToString();
    var LoggedUserStatus = HttpContext.Current.Session["LoggedUserStatus"].ToString();

    if (LoggedUserTp == "AslSuperadmin" && LoggedUserStatus == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

}


@if (Model != null)
{
    <div class="panel panel-primary">
        <div class="panel-heading">Calendar Image Information</div>
        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th>
                        Year
                    </th>
                    <th>
                        Month
                    </th>
                    <th>
                        File-Url
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    String Month = "";
                    if (item.Month == "01")
                    {
                        Month = "January";
                    }
                    else if (item.Month == "02")
                    {
                        Month = "February";
                    }
                    else if (item.Month == "03")
                    {
                        Month = "March";
                    }
                    else if (item.Month == "04")
                    {
                        Month = "April";
                    }
                    else if (item.Month == "05")
                    {
                        Month = "May";
                    }
                    else if (item.Month == "06")
                    {
                        Month = "June";
                    }
                    else if (item.Month == "07")
                    {
                        Month = "July";
                    }
                    else if (item.Month == "08")
                    {
                        Month = "August";
                    }
                    else if (item.Month == "09")
                    {
                        Month = "September";
                    }
                    else if (item.Month == "10")
                    {
                        Month = "October";
                    }
                    else if (item.Month == "11")
                    {
                        Month = "November";
                    }
                    else if (item.Month == "12")
                    {
                        Month = "December";
                    }
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Year)
                        </td>
                        <td>
                            @Month
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.FilePath)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
}