cloud_rx/AslPrescriptionApi/Controllers/ASL/SmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using AslPrescriptionApi.Models;
using AslPrescriptionApi.Models.ASL;
using AslPrescriptionApi.Models.DTO;
using Microsoft.SqlServer.Server;

namespace AslPrescriptionApi.Controllers.ASL
{
    public class SmsController : AppController
    {
        private AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();

        //Datetime formet
        IFormatProvider dateformat = new System.Globalization.CultureInfo("fr-FR", true);
        TimeZoneInfo timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
        public DateTime td;

        //Get Ip ADDRESS,Time & user PC Name
        public string strHostName;
        public IPHostEntry ipHostInfo;
        public IPAddress ipAddress;

        public SmsController()
        {
            strHostName = System.Net.Dns.GetHostName();
            ipHostInfo = Dns.Resolve(Dns.GetHostName());
            ipAddress = ipHostInfo.AddressList[0];
            td = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
            ViewData["HighLight_Menu_PromotionForm"] = "High Light Menu";
        }






        // GET: /SMS/
        public ActionResult Index()
        {
            WebClient chcksmsqtySndSms = new WebClient();
            //string userName = "asl-sms";
            //string usPss = "asl.123SMS@3412";

            Int64 LoggedCompId = Convert.ToInt64(System.Web.HttpContext.Current.Session["loggedCompID"]);
            var getSMSUserNamePass = from m in db.AslCompanyDbSet
                                     where m.COMPID == LoggedCompId
                                     select new { m.SMSIDP, m.SMSPWP };
            string userName = "", usPss = "";
            foreach (var VARIABLE in getSMSUserNamePass)
            {
                userName = VARIABLE.SMSIDP;
                usPss = VARIABLE.SMSPWP;
            }

            string qty = "";
            if (userName == null || usPss == null)
            {
                qty = "0";
            }
            else
            {
                qty = chcksmsqtySndSms.DownloadString("http://app.itsolutionbd.net/api/command?username=" + userName + "&password=" + usPss + "&cmd=Credits");
            }
            TempData["CheckSMSQuantity"] = qty;
            return View();
        }



        [HttpPost]
        public ActionResult Index(MailDTO model)
        {
            if (ModelState.IsValid)
            {
                if (model.GROUPID == null && model.MobileNo == null)
                {
                    ViewBag.SMSMessage = "Select group name or Mobile number filed first!";
                    return View("Index");
                }


                WebClient chcksmsqtySndSms = new WebClient();
                string senderName = "ALCHEMY-BD";
                //string userName = "asl-sms";
                //string usPss = "asl.123SMS@3412";

                var getSMSUserNamePass = from m in db.AslCompanyDbSet
                                         where m.COMPID == model.COMPID
                                         select new { m.SMSIDP, m.SMSPWP };
                string userName = "", usPss = "";
                foreach (var VARIABLE in getSMSUserNamePass)
                {
                    userName = VARIABLE.SMSIDP;
                    usPss = VARIABLE.SMSPWP;
                }

                if (userName != "" && usPss != "")
                {
                    try
                    {
                        string qty = chcksmsqtySndSms.DownloadString("http://app.itsolutionbd.net/api/command?username=" + userName + "&password=" + usPss + "&cmd=Credits");
                        TempData["CheckSMSQuantity"] = qty;

                        WebClient cardsms = new WebClient();
                        string cashStatus = "";

                        //Current group contact list add in ASL_PEMAIL table. 
                        if (model.GROUPID != null)
                        {
                            var getUploadContactList = (from m in db.UploadContactDbSet where m.COMPID == model.COMPID && m.GROUPID == model.GROUPID select new{m.MOBNO1,m.MOBNO2}).ToList();
                            foreach (var addList in getUploadContactList)
                            {
                                if (BdNumberValidate(addList.MOBNO1))
                                {
                                    string mobileNo = addList.MOBNO1;
                                    Insert_ASL_PSMS_Table(model,mobileNo);
                                }
                                if (BdNumberValidate(addList.MOBNO2))
                                {
                                    string mobileNo = addList.MOBNO2;
                                    Insert_ASL_PSMS_Table(model,mobileNo);
                                }
                            }
                        }


                        //model.ToEmail list add in ASL_PEMAIL Table.
                        if (model.MobileNo != null)
                        {
                            string[] multi = model.MobileNo.Split(',');
                            foreach (var multiemailId in multi)
                            {
                                if (multiemailId != "" && BdNumberValidate(multiemailId))
                                {
                                    string mobileNo = multiemailId;
                                    Insert_ASL_PSMS_Table(model,mobileNo);
                                }
                            }
                        }



                        string currentDate = td.ToString("yyyy-MM-dd");
                        DateTime transdate = Convert.ToDateTime(currentDate.Substring(0, 10));
                        Int64 year = Convert.ToInt64(td.ToString("yyyy"));
                        var find_ASLPSMS = (from m in db.SendLogSMSDbSet where m.COMPID == model.COMPID && m.TRANSDT == transdate && m.TRANSYY == year && m.STATUS == "PENDING" select m).ToList();
                        Int64 countSms = 0;
                        foreach (var x in find_ASLPSMS)
                        {
                            if (model.Language == "ENG")
                                cashStatus = cardsms.DownloadString("http://app.itsolutionbd.net/api/sendsms/plain?user=" + userName +
                                                   "&password=" + usPss + "&sender=" + senderName + "&SMSText=" + model.Body + "&GSM=" +
                                                   x.MOBNO);
                            else
                                cashStatus = cardsms.DownloadString("http://app.itsolutionbd.net/api/sendsms/plain?user=" + userName +
                                                   "&password=" + usPss + "&sender=" + senderName + "&SMSText=" + model.Body + "&GSM=" +
                                                    x.MOBNO + "&type=longSMS&datacoding=8");

                            if (GetApiResponseCodeMeaning(cashStatus) == "Request was successful")
                            {
                                countSms++;
                                Update_ASL_PSMS_Table_SendingEmail(x, model);
                            }
                        }



                        //  if ((cashStatus == "-1") || (cashStatus == "-2") || (cashStatus == "-3") || (cashStatus == "-5") ||
                        //(cashStatus == "-6") || (cashStatus == "-10") || (cashStatus == "-11") ||
                        //(cashStatus == "-13") || (cashStatus == "-22") || (cashStatus == "-23") || (cashStatus == "-26") ||
                        //(cashStatus == "-27") || (cashStatus == "-28") || (cashStatus == "-29") || (cashStatus == "-30") ||
                        //(cashStatus == "-33") || (cashStatus == "-34") || (cashStatus == "-99"))
                        //  {
                        //      ViewBag.SMSMessage = "Sms not sent.";
                        //      return View();
                        //  }
                        //  else
                        //  {
                        //      TempData["SMSMessage"] = "Sms sent.";
                        //      return RedirectToAction("Index");
                        //  }


                        if (countSms != 0)
                        {
                            TempData["SMSMessage"] = "Sending Done in " + countSms + " sms.";
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.SMSMessage = "Sms not sent.";
                            return View("Index");
                        }

                    }
                    catch (Exception ex)
                    {
                        Response.Write(ex.Message);
                        ViewBag.SMSMessage = "Sending Failed!!";
                        return View();
                    }

                }
                else
                {
                    ViewBag.SMSMessage = "Your SMS id not registered!!";
                    return View("Index");
                }

            }
            return View();
        }






        private bool BdNumberValidate(string number)
        {
            try
            {
                if (number.Length > 13 || number.Length < 13)
                {
                    return false;
                }
                else
                {
                    string operatorCode = number.Substring(0, 5);
                    switch (operatorCode)
                    {
                        case "88018":
                        case "88017":
                        case "88019":
                        case "88016":
                        case "88011":
                        case "88015":
                            return true; //all of the operator in case is return true

cloud_rx/AslPrescriptionApi/Views/Sms/Index.cshtml
@using System.Web.Optimization
@using AslPrescriptionApi.Models
@model AslPrescriptionApi.Models.DTO.MailDTO
@{
    ViewBag.Title = "Index";

    if (HttpContext.Current.Session["LoggedUserType"] == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

    var LoggedUserTp = HttpContext.Current.Session["LoggedUserType"].ToString();
    var LoggedUserStatus = HttpContext.Current.Session["LoggedUserStatus"].ToString();
    var LoggedCompanyStatus = HttpContext.Current.Session["LoggedCompanyStatus"].ToString();

    if ((LoggedUserTp == "CompanyAdmin" || LoggedUserTp == "UserAdmin" || LoggedUserTp == "User") && LoggedUserStatus == "A" && LoggedCompanyStatus == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }

    Int64 LoggedCompId = Convert.ToInt64(HttpContext.Current.Session["loggedCompID"].ToString());
    Int64 LoggedUserId = Convert.ToInt64(HttpContext.Current.Session["loggedUserID"].ToString());
    AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();


    string companyName = "";
    var findComanyName = (from m in db.AslCompanyDbSet where m.COMPID == LoggedCompId select new { m.COMPNM });
    foreach (var comp in findComanyName)
    {
        companyName = comp.COMPNM;
    }



    List<SelectListItem> listOfGroupame = new List<SelectListItem>();
    var result = (from n in db.UploadGroupDbSet
                  where n.COMPID == LoggedCompId
                  select n).ToList();

    foreach (var n in result)
    {
        Int64 count = 0;
        var totalMobileNO_1 = (from m in db.UploadContactDbSet where n.COMPID == m.COMPID && m.GROUPID == n.GROUPID && m.MOBNO1 != null select m.MOBNO1).ToList();
        foreach (var c in totalMobileNO_1)
        {
            count++;
        }
        var totalMobileNO_2 = (from m in db.UploadContactDbSet where n.COMPID == m.COMPID && m.GROUPID == n.GROUPID && m.MOBNO2 != null select m.MOBNO2).ToList();
        foreach (var c in totalMobileNO_2)
        {
            count++;
        }
        string groupNameWithCount = Convert.ToString(n.GROUPNM + " | " + count);
        listOfGroupame.Add(new SelectListItem { Text = groupNameWithCount, Value = n.GROUPID.ToString() });
    }


    var permission_Check = from m in db.AslRoleDbSet where m.COMPID == LoggedCompId && m.USERID == LoggedUserId && m.CONTROLLERNAME == "sms" select m;
    var Status = "";
    foreach (var check in permission_Check)
    {
        Status = check.STATUS;
    }


    if (Status == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }
}


<!-- INSTRUCTIONS -->
<!-- 2 CSS files are required: -->
<!--   * Tag-it's base CSS (jquery.tagit.css). -->
<!--   * Any theme CSS (either a jQuery UI theme such as "flick", or one that's bundled with Tag-it, e.g. tagit.ui-zendesk.css as in this example.) -->
<!-- The base CSS and tagit.ui-zendesk.css theme are scoped to the Tag-it widget, so they shouldn't affect anything else in your site, unlike with jQuery UI themes. -->
<link href="../../Content/tag-it-CSS/jquery.tagit.css" rel="stylesheet" />
<link href="../../Content/tag-it-CSS/tagit.ui-zendesk.css" rel="stylesheet" />
<!-- If you want the jQuery UI "flick" theme, you can use this instead, but it's not scoped to just Tag-it like tagit.ui-zendesk is: -->
<!--   <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css"> -->
<!-- jQuery and jQuery UI are required dependencies. -->
<!-- Although we use jQuery 1.4 here, it's tested with the latest too (1.8.3 as of writing this.) -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>

<!-- The real deal -->
@*<script src="~/Scripts/tag-it/tag-it.js"></script>*@
<script src="../../Scripts/tag-it/tag-it.js"></script>

@using (Html.BeginForm())
{

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    //Its not mandatory field its used because this is required attribute. That why default value inserted.
    @Html.HiddenFor(model => model.COMPID, htmlAttributes: new { @class = "form-control", @Value = LoggedCompId ,id = "txtHiddenCompid"})
    @Html.HiddenFor(model => model.Subject, htmlAttributes: new { @class = "form-control", @Value = "Subject" })
    @Html.HiddenFor(model => model.CompanyName, htmlAttributes: new { @class = "form-control", @Value = companyName })

    <div id="contentHeaderBox">
        @if (TempData["SMSMessage"] != null)
        {
            <h1 style="padding-left: 16px;">Sending SMS <span style="color: red; padding-left: 81px;">@TempData["SMSMessage"]</span> </h1>
        }
        else if (ViewBag.SMSMessage != null)
        {
            <h1 style="padding-left: 16px;">Sending SMS <span style="color: red; padding-left: 70px;">@ViewBag.SMSMessage</span> </h1>
        }
        else
        {
            <h1 style="padding-left:16px">Sending SMS</h1>
        }
        <div class="btn-group pull-right" id="editOption">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-expanded="false">
                <i class="fa fa-cog"></i>
            </button>
            <ul class="dropdown-menu pull-right" style="" role="menu">
                <li>
                    <a href="@Url.Action("getPendingSMS", "Sms")"><i class="fa fa-file-text"></i> Pending SMS Info.</a>
                </li>
            </ul>
        </div>
    </div>
    <br />
    <div class="col-md-12" ng-app="">
        <div class="form-group">
            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.Label("name", "Select Group: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-4">
                    @Html.DropDownListFor(model => model.GROUPID, listOfGroupame, "-Select Group Name-", new { @class = "form-control", id = "ddlGroupnameID", autofocus = true })
                </div>
                <div class="col-md-2 text-right" style="font-size: 20px">
                    @Html.Label("name", "Credit: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3 text-left" style="font-size: 20px">
                    <label>@TempData["CheckSMSQuantity"] </label>
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.Label("name", "To Mobile: ")
                </div>
                <div class="col-md-8">
                    @Html.TextBoxFor(model => model.MobileNo, htmlAttributes: new { @class = "form-control", id = "myULTags" })
                    @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.Label("name", "Language: ")
                </div>
                <div class="col-md-8">
                    @Html.RadioButtonFor(model => model.Language, "ENG", htmlAttributes: new { @class = "radio-inline", id = "btnEng", @checked = "checked" }) English
                    @Html.RadioButtonFor(model => model.Language, "BNG", htmlAttributes: new { @class = "radio-inline", id = "btnBan" }) Bangla
                </div>
            </div>


            <br />
            <div class="row">
                <div class="col-md-3">
                    @Html.Label("name", "Message Body: ")
                </div>
                <div class="col-md-5">
                    <textarea class="form-control"
                              cols="20"
                              id="Body"
                              name="Body"
                              rows="4" ng-model="Body" maxlength="158"></textarea>
                    @*@Html.TextAreaFor(model => model.Body, htmlAttributes: new { @class = "form-control",  data_ng_model = "Body", MaxLength = "158", Height = "150px", })*@
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3" id="charleft" style="color: green;">
                    <span class="a" ng-bind="158-Body.length+'&nbsp;&nbsp;Character left'"
                          ng-class="{'btn-warning': Body.length >= 120, 'btn-danger': Body.length >= 141 }"></span>
                    <span class="b" ng-bind="(158/2-Body.length) +'&nbsp;&nbsp;Character left'" hidden=""
                          ng-class="{'btn-warning': Body.length >= 50, 'btn-danger': Body.length >= 75 }"></span>
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-2">
                    <input type="submit" class="btn btn-primary btn-block" value="Send" />
                </div>
            </div>
        </div>
    </div>


    <script>
        $(document).ready(function () {

            $(".a").show();

            $("#btnEng").click(function () {
                $(".b").hide();
                $(".a").show();
            });
            $("#btnBan").click(function () {
                $(".b").show();
                $(".a").hide();
            });

            //-------------------------------
            // Preloading data in markup
            //-------------------------------
            $('#myULTags').tagit({
                allowSpaces: true,
                minLength: 2,
                removeConfirmation: true,
                tagSource: function (request, response) {
                    //console.log("1");
                    $.ajax({
                        url: '@Url.Action("TagSearch_tagit", "Sms")',
                        data: {
                            term: request.term,
                            compid: $('#txtHiddenCompid').val()
                        },
                        dataType: "json",
                        success: function (data) {
                            response($.map(data, function (item) {
                                return {
                                    label: item,
                                    value: item
                                };
                            }));
                        }
                    });
                }
            });

        });
    </script>



    <style type="text/css">
        .ui-autocomplete {
            position: absolute;
            cursor: default;
            background: #f0ffff;
            max-height: 200px;
            overflow-y: auto;
            /* prevent horizontal scrollbar */
            overflow-x: hidden;
            /* add padding to account for vertical scrollbar */
            padding-right: 20px;
        }
    </style>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}



<script src="../../Scripts/angularjs/1.0.5/angular.js"></script>

cloud_rx/AslPrescriptionApi/Views/Sms/getPendingSMS.cshtml
@using System.Web.Optimization
@using AslPrescriptionApi.Models
@using AslPrescriptionApi.Models.ASL
@model AslPrescriptionApi.Models.DTO.PendingMailSmsDTO
@{
    ViewBag.Title = "getPendingSMS";

    if (HttpContext.Current.Session["LoggedUserType"] == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

    var LoggedUserTp = HttpContext.Current.Session["LoggedUserType"].ToString();
    var LoggedUserStatus = HttpContext.Current.Session["LoggedUserStatus"].ToString();
    var LoggedCompanyStatus = HttpContext.Current.Session["LoggedCompanyStatus"].ToString();

    if ((LoggedUserTp == "CompanyAdmin" || LoggedUserTp == "UserAdmin" || LoggedUserTp == "User") && LoggedUserStatus == "A" && LoggedCompanyStatus == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }

    Int64 LoggedCompId = Convert.ToInt64(HttpContext.Current.Session["loggedCompID"].ToString());
    Int64 LoggedUserId = Convert.ToInt64(HttpContext.Current.Session["loggedUserID"].ToString());
    AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();

    TimeZoneInfo timeZoneInfo;
    timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
    DateTime currentDateTime = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);

    var permission_Check = from m in db.AslRoleDbSet where m.COMPID == LoggedCompId && m.USERID == LoggedUserId && m.CONTROLLERNAME == "sms" select m;
    var Status = "";
    foreach (var check in permission_Check)
    {
        Status = check.STATUS;
    }


    if (Status == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }
}



<link href="~/Content/bootstrap%20datepicker%20css/datepicker.css" rel="stylesheet" />
<link href="~/Content/bootstrap%20datepicker%20css/datepicker3.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap-datepicker.js"></script>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.COMPID, htmlAttributes: new { @Value = LoggedCompId })
    @Html.HiddenFor(model => model.UPDUSERID, new { @Value = LoggedUserId })

    <div id="contentHeaderBox">
        @if (ViewBag.PendingSMSMessage != null)
        {
            <h1 style="padding-left: 16px;">Pending SMS <span style="color: red; padding-left: 70px;">@ViewBag.PendingSMSMessage</span> </h1>
        }
        else
        {
            <h1 style="padding-left:16px">Pending SMS</h1>
        }

        <div class="btn-group pull-right" id="editOption">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-expanded="false">
                <i class="fa fa-cog"></i>
            </button>
            <ul class="dropdown-menu pull-right" style="" role="menu">
                <li>
                    <a href="@Url.Action("Index", "Sms")"><i class="fa fa-file-text"></i> Sending SMS</a>
                </li>
            </ul>
        </div>
    </div>
    <br />
    <div class="col-md-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-1">
                    @Html.Label("name", "Date: ", htmlAttributes: new { @class = "control-label", })
                </div>
                <div class="col-md-2">
                    @Html.TextBoxFor(model => model.TRANSDT, htmlAttributes: new
                    {
                        @class = "form-control  input-sm",
                        id = "txtTransDate", @*@Value = currentDateTime.ToString("dd-MMM-yyyy")*@ })
                    @Html.ValidationMessageFor(model => model.TRANSDT, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-2 text-right" style="font-size: 20px">
                    @Html.Label("name", "Credit: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3 text-left" style="font-size: 20px">
                    <label>@TempData["CheckSMSQuantity"] </label>
                </div>
                @if (ViewData["PendingList_SMS"] != null)
                {
                    <div class="col-md-2"></div>
                    <div class="col-md-2">
                        <input type="submit" class="btn btn-primary btn-block" value="Send" name="command" id="btnSending" style="float: right" data-loading-text="Sending...." />
                    </div>
                }
                <input type="submit" class="btn btn-primary btn-block" value="Search" name="command" id="btnSearch" />
            </div>


            @if (ViewData["PendingList_SMS"] != null)
            {
                @*<br />
                    <div class="row">
                        <div class="col-md-2">
                            <input type="submit" class="btn btn-primary btn-block" value="Send" name="command" id="btnSending" style="float: right" data-loading-text="Sending...." />
                        </div>
                    </div>*@


                List<ASL_PSMS> pendingList = new List<ASL_PSMS>();
                pendingList = (List<ASL_PSMS>)ViewData["PendingList_SMS"];
                Int64 count = 0;
                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-danger">
                            <div class="panel-heading">Pending list </div>
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tr>
                                        <th>
                                            Serial
                                        </th>
                                        <th>
                                            Mobile No
                                        </th>
                                        <th>
                                            Message
                                        </th>
                                        <th>
                                            Status
                                        </th>
                                    </tr>

                                    @foreach (var item in pendingList)
                                    {
                                        count++;
                                        <tr>
                                            <td>
                                                @count
                                            </td>
                                            <td>
                                                @item.MOBNO
                                            </td>
                                            <td>
                                                @item.MESSAGE
                                            </td>
                                            <td>
                                                @item.STATUS
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @Html.TextBoxFor(model => model.UPDLTUDE, new { id = "latlon", style = "display: none;" })
            <input id="lat" type="hidden" />
            <input id="lon" type="hidden" />
        </div>
    </div>



    //Latitute & longitude
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script language="javascript" type="text/javascript">
        $(function () {
            navigator.geolocation.getCurrentPosition(showPosition);
            //navigator.geolocation.getCurrentPosition(showPosition, positionError);

            function showPosition(position) {
                var coordinates = position.coords;
                $("#lat").val(coordinates.latitude);
                $("#lon").val(coordinates.longitude);

                $("#latlon").val(
                    $("#lat").val() + "," + $("#lon").val()
                );
            }
        });
    </script>


    <script type="text/javascript">

        $(document).ready(function () {

            $('#btnSearch').bind("keyup keypress", function (e) { // Enter button disable when push the enter button in TextBox
                var code = e.keyCode || e.which;
                if (code == 13) {
                    e.preventDefault();
                    return false;
                }
            });


            $('#btnSearch').hide();


            $('#txtTransDate').datepicker({
                format: "dd-M-yyyy",
                autoclose: true,
                todayHighlight: true,
                showOnFocus: true,
                //format: "yyyy-M-dd"
            }).on('show', function (e) {
                if (e.date) {
                    $(this).data('stickyDate', e.date);
                } else {
                    $(this).data('stickyDate', null);
                }
            }).on('hide', function (e) {
                var stickyDate = $(this).data('stickyDate');

                if (!e.date && stickyDate) {
                    $(this).datepicker('setDate', stickyDate);
                    $(this).data('stickyDate', null);
                }
                $('#btnSearch').click();
            });


            $('.btn').on('click', function () {
                var $this = $(this);
                $this.button('loading');
                setTimeout(function () {
                    $this.button('reset');
                }, 8000);
            });
        });
    </script>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}