cloud_rx/AslPrescriptionApi/Controllers/ASL/UploadContactController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AslPrescriptionApi.Models;
using AslPrescriptionApi.Models.ASL;
using AslPrescriptionApi.Models.DTO;

namespace AslPrescriptionApi.Controllers.ASL
{
    public class UploadContactController : AppController
    {
        private AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();


        //Datetime formet
        IFormatProvider dateformat = new System.Globalization.CultureInfo("fr-FR", true);
        TimeZoneInfo timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
        public DateTime td;

        //Get Ip ADDRESS,Time & user PC Name
        public string strHostName;
        public IPHostEntry ipHostInfo;
        public IPAddress ipAddress;

        public UploadContactController()
        {
            strHostName = System.Net.Dns.GetHostName();
            ipHostInfo = Dns.Resolve(Dns.GetHostName());
            ipAddress = ipHostInfo.AddressList[0];
            td = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
            ViewData["HighLight_Menu_PromotionForm"] = "High Light Menu";
        }




        public ASL_LOG aslLog = new ASL_LOG();

        // Delete ALL INFORMATION from Grid(Upload Contact data) TO Asl_lOG Database Table.
        public void Delete_Upload_LogData(ASL_PCONTACTS model)
        {
            TimeZoneInfo timeZoneInfo;
            timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
            DateTime PrintDate = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
            var date = Convert.ToString(PrintDate.ToString("dd-MMM-yyyy"));
            var time = Convert.ToString(PrintDate.ToString("hh:mm:ss tt"));

            Int64 maxSerialNo = Convert.ToInt64((from n in db.AslLogDbSet where n.COMPID == model.COMPID && n.USERID == model.INSUSERID select n.LOGSLNO).Max());
            if (maxSerialNo == 0)
            {
                aslLog.LOGSLNO = Convert.ToInt64("1");
            }
            else
            {
                aslLog.LOGSLNO = maxSerialNo + 1;
            }

            aslLog.COMPID = Convert.ToInt64(model.COMPID);
            aslLog.USERID = model.INSUSERID;
            aslLog.LOGTYPE = "DELETE";
            aslLog.LOGSLNO = aslLog.LOGSLNO;
            aslLog.LOGDATE = Convert.ToDateTime(date);
            aslLog.LOGTIME = Convert.ToString(time);
            aslLog.LOGIPNO = ipAddress.ToString();
            aslLog.LOGLTUDE = model.INSLTUDE;
            aslLog.TABLEID = "ASL_PCONTACTS";

            string groupName = "";
            var findGroupName = (from m in db.UploadGroupDbSet where m.COMPID == model.COMPID && m.GROUPID == model.GROUPID select m).ToList();
            foreach (var x in findGroupName)
            {
                groupName = x.GROUPNM.ToString();
            }

            aslLog.LOGDATA = Convert.ToString("When upload File then duplicate data deleted. Group Name: " + groupName + ",\nName: " + model.NAME + ",\nEmail: " + model.EMAIL + ",\nMobile No 1: " + model.MOBNO1 + ",\nMobile No 2: " + model.MOBNO2 + ",\nAddress: " + model.ADDRESS + ".");
            aslLog.USERPC = strHostName;

            db.AslLogDbSet.Add(aslLog);
            db.SaveChanges();
        }





        public ASL_DELETE AslDelete = new ASL_DELETE();

        // Delete ALL INFORMATION from TO ASL_DELETE Database Table.
        public void Delete_Upload_LogDelete(ASL_PCONTACTS model)
        {
            TimeZoneInfo timeZoneInfo;
            timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById("Central Asia Standard Time");
            DateTime PrintDate = TimeZoneInfo.ConvertTime(DateTime.Now, timeZoneInfo);
            var date = Convert.ToString(PrintDate.ToString("dd-MMM-yyyy"));
            var time = Convert.ToString(PrintDate.ToString("hh:mm:ss tt"));

            Int64 maxSerialNo = Convert.ToInt64((from n in db.AslDeleteDbSet where n.COMPID == model.COMPID && n.USERID == model.INSUSERID select n.DELSLNO).Max());
            if (maxSerialNo == 0)
            {
                AslDelete.DELSLNO = Convert.ToInt64("1");
            }
            else
            {
                AslDelete.DELSLNO = maxSerialNo + 1;
            }

            AslDelete.COMPID = Convert.ToInt64(model.COMPID);
            AslDelete.USERID = model.INSUSERID;
            AslDelete.DELSLNO = AslDelete.DELSLNO;
            AslDelete.DELDATE = Convert.ToString(date);
            AslDelete.DELTIME = Convert.ToString(time);
            AslDelete.DELIPNO = ipAddress.ToString();
            AslDelete.DELLTUDE = model.INSLTUDE;
            AslDelete.TABLEID = "ASL_PCONTACTS";

            string groupName = "";
            var findGroupName = (from m in db.UploadGroupDbSet where m.COMPID == model.COMPID && m.GROUPID == model.GROUPID select m).ToList();
            foreach (var x in findGroupName)
            {
                groupName = x.GROUPNM.ToString();
            }
            AslDelete.DELDATA = Convert.ToString("When upload File then duplicate data deleted. Group Name: " + groupName + ",\nName: " + model.NAME + ",\nEmail: " + model.EMAIL + ",\nMobile No 1: " + model.MOBNO1 + ",\nMobile No 2: " + model.MOBNO2 + ",\nAddress: " + model.ADDRESS + ".");
            AslDelete.USERPC = strHostName;

            db.AslDeleteDbSet.Add(AslDelete);
            db.SaveChanges();
        }




        private bool IsValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }
        }



        private bool BdNumberValidate(string number)
        {
            try
            {
                if (number.Length > 13 || number.Length < 13)
                {
                    return false;
                }
                else
                {
                    string operatorCode = number.Substring(0, 5);
                    switch (operatorCode)
                    {
                        case "88018":
                        case "88017":
                        case "88019":
                        case "88016":
                        case "88011":
                        case "88015":
                            return true; //all of the operator in case is return true
                            break;
                        default:
                            return false; //other operator code return false
                    }
                }
            }
            catch
            {
                return false;
            }
        }









        // GET: /UploadDocument/
        public ActionResult UploadDocument()
        {
            return View();
        }

        // POST: /UploadDocument/
        [HttpPost]
        public ActionResult UploadDocument(HttpPostedFileBase file, ASL_PCONTACTS model)
        {
            DataSet ds = new DataSet();
            String fileLocation = "";
            Int64 count = 0;
            try
            {
                if (Request.Files["file"].ContentLength > 0)
                {

                    string fileExtension = System.IO.Path.GetExtension(Request.Files["file"].FileName);

                    if (fileExtension == ".xls" || fileExtension == ".xlsx")
                    {
                        fileLocation = string.Concat(Server.MapPath("~/UploadFile/CurrentFile/") + model.COMPID + Request.Files["file"].FileName);
                        if (System.IO.File.Exists(fileLocation))
                        {
                            System.IO.File.Delete(fileLocation);
                        }
                        Request.Files["file"].SaveAs(fileLocation);
                        string excelConnectionString = string.Empty;

                        //connection String for xls file format.
                        if (fileExtension == ".xls")
                        {
                            excelConnectionString = "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 8.0;HDR=Yes;IMEX=2\"";
                        }
                        //connection String for xlsx file format.
                        else if (fileExtension == ".xlsx")
                        {
                            //excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=2\"";
                            excelConnectionString = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source= " + fileLocation + ";Extended Properties=\"Excel 12.0;HDR=Yes;IMEX=1\"";
                        }
                        //Create Connection to Excel work book and add oledb namespace
                        OleDbConnection excelConnection = new OleDbConnection(excelConnectionString);
                        excelConnection.Open();
                        DataTable dt = new DataTable();

                        dt = excelConnection.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                        if (dt == null)
                        {
                            return null;
                        }

                        String[] excelSheets = new String[dt.Rows.Count];
                        int t = 0;
                        //excel data saves in temp file here.
                        foreach (DataRow row in dt.Rows)
                        {
                            excelSheets[t] = row["TABLE_NAME"].ToString();
                            t++;
                        }
                        OleDbConnection excelConnection1 = new OleDbConnection(excelConnectionString);


                        try
                        {

cloud_rx/AslPrescriptionApi/Views/UploadContact/UploadDocument.cshtml
@using AslPrescriptionApi.Models
@using AslPrescriptionApi.Models.DTO
@model AslPrescriptionApi.Models.ASL.ASL_PCONTACTS

@{
    ViewBag.Title = "UploadDocument";


    if (HttpContext.Current.Session["LoggedUserType"] == null)
    {
        Response.Redirect(Url.Action("Index", "Login"));
    }

    var LoggedUserTp = HttpContext.Current.Session["LoggedUserType"].ToString();
    var LoggedUserStatus = HttpContext.Current.Session["LoggedUserStatus"].ToString();
    var LoggedCompanyStatus = HttpContext.Current.Session["LoggedCompanyStatus"].ToString();

    if ((LoggedUserTp == "CompanyAdmin" || LoggedUserTp == "UserAdmin" || LoggedUserTp == "User") && LoggedUserStatus == "A" && LoggedCompanyStatus == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }


    Int64 LoggedUserId = Convert.ToInt64(HttpContext.Current.Session["loggedUserID"].ToString());
    Int64 LoggedCompId = Convert.ToInt64(HttpContext.Current.Session["loggedCompID"].ToString());
    AslPrescriptionApiDbContext db = new AslPrescriptionApiDbContext();


    List<SelectListItem> listOfGroupame = new List<SelectListItem>();
    var result = (from n in db.UploadGroupDbSet
                  where n.COMPID == LoggedCompId
                  select n).ToList();

    foreach (var n in result)
    {
        listOfGroupame.Add(new SelectListItem { Text = n.GROUPNM, Value = n.GROUPID.ToString() });
    }


    var permission_Check = from m in db.AslRoleDbSet where m.COMPID == LoggedCompId && m.USERID == LoggedUserId && m.CONTROLLERNAME == "uploadcontact" select m;
    var Status = "";
    foreach (var check in permission_Check)
    {
        Status = check.STATUS;
    }


    if (Status == "A")
    {

    }
    else
    {
        Response.Redirect(Url.Action("Index", "Logout"));
    }
}


@using (Html.BeginForm("UploadDocument", "UploadContact", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    @Html.HiddenFor(model => model.COMPID, new { @Value = LoggedCompId })
    @Html.HiddenFor(model => model.INSUSERID, new { @Value = LoggedUserId })

    <div id="contentHeaderBox">
        <h1>Group wise contact upload</h1>
        <div class="btn-group pull-right" id="editOption">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" aria-expanded="false">
                <i class="fa fa-cog"></i>
            </button>
            <ul class="dropdown-menu pull-right" style="" role="menu">
                <li>
                    <a href="@Url.Action("GroupView", "UploadGroup")"><i class="fa fa-file-text"></i> Contact Group</a>
                    <a href="@Url.Action("EditContact", "UploadEdit")"><i class="fa fa-file-text"></i> Edit Contact</a>
                </li>
            </ul>
        </div>
    </div>
    <br />

    <div class="col-md-12">
        <div class="form-group">


            <div class="row">
                <div class="col-md-12">
                    <p>Please upload xls/xlxs file with specific format</p>
                    <p><strong>NB:</strong> Excel file must have fixed column name <strong>(NAME,EMAIL,MOBILE1,MOBILE2,ADDRESS)</strong></p>
                    <a href="~/UploadFile/ContactFormat.xls" style="color: blue">Download sample file</a>
                    <ul>
                        <li>
                            <strong>name</strong> required
                        </li>
                        <li>
                            <strong>email</strong> or <strong>mobileno1</strong>(mobile number like 8801xxxxxxxxx -13 digit) required
                        </li>
                    </ul>
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-md-2">
                    @Html.Label("name", "Select Group: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    @Html.DropDownListFor(model => model.GROUPID, listOfGroupame, "-Select Group Name-", new { @class = "form-control", id = "ddlGroupnameID", autofocus = true })
                </div>
            </div>

            <br />
            <div class="row" id="UploadContent">
                <div class="col-md-2">
                    @Html.Label("name", "Upload Excel File: ", htmlAttributes: new { @class = "control-label" })
                </div>
                <div class="col-md-3">
                    <input type="file" id="FileUpload" name="file" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
                    @if (ViewBag.UploadMessage != null)
                    {
                        <h4 style="color: #226699">@ViewBag.UploadMessage</h4>
                    }
                </div>
                <div class="col-md-2">
                    <input type="submit" class="btn btn-primary" value="Process" style="float: right;" id="load" data-loading-text="Uploading...." />
                </div>
            </div>



            @if (TempData["ErrorUploadList"] != null)
            {
                List<UploadContactDTO> errorUploadList = new List<UploadContactDTO>();
                errorUploadList = (List<UploadContactDTO>)TempData["ErrorUploadList"];

                <br />
                <div class="row">
                    <div class="col-md-12">
                        <div class="panel panel-danger">
                            <div class="panel-heading">Error List- This list doesn't add in database!!!!! </div>
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <tr>
                                        <th>
                                            Name
                                        </th>
                                        <th>
                                            Email
                                        </th>
                                        <th>
                                            Mobile No 1
                                        </th>
                                        <th>
                                            Mobile No 2
                                        </th>
                                        <th>
                                            Address
                                        </th>
                                    </tr>

                                    @foreach (var item in errorUploadList)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.NAME)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EMAIL)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MOBNO1)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.MOBNO2)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ADDRESS)
                                            </td>
                                        </tr>
                                    }

                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            }

            @Html.TextBoxFor(model => model.INSLTUDE, new { id = "latlon", style = "display: none;" })
            <input id="lat" type="hidden" />
            <input id="lon" type="hidden" />
        </div>
    </div>


    //Latitute & longitude
    <script src="http://maps.google.com/maps/api/js?sensor=false"></script>

    <script language="javascript" type="text/javascript">
        $(function () {
            navigator.geolocation.getCurrentPosition(showPosition);
            //navigator.geolocation.getCurrentPosition(showPosition, positionError);

            function showPosition(position) {
                var coordinates = position.coords;
                $("#lat").val(coordinates.latitude);
                $("#lon").val(coordinates.longitude);

                $("#latlon").val(
                    $("#lat").val() + "," + $("#lon").val()
                );
            }
        });
    </script>


    <script type="text/javascript">

        $(document).ready(function () {

            var groupID = $('#ddlGroupnameID').val();
            if (groupID == "") {
                $('#UploadContent').hide();
            } else {
                $('#UploadContent').show();
            }

            $('#ddlGroupnameID').change(function () {
                var groupID = $('#ddlGroupnameID').val();
                if (groupID == "") {
                    $('#UploadContent').hide();
                } else {
                    $('#UploadContent').show();
                }
            });


            $('.btn').on('click', function () {
                var $this = $(this);
                $this.button('loading');
                setTimeout(function () {
                    $this.button('reset');
                }, 8000);
            });
        });
    </script>

}